### ISSUE TITLE
Automatic remove of tmp files created by generators

### ISSUE THREAD

**Issue by CecileDages** [OpenFLUID/openfluid#1026]

**Comment by jctophefabre** [comment]
Thanks Cecile for the issue.

This automatic removal concerns the generators that use temporary files.
The behaviour of these generators should be:
* remove all created temporary files when they are not needed anymore (may be in `finalizeRun()` or in an earlier stage
* by default, this removal is enabled
* the removal can be disabled (files are kept at the end of the simulation) using a command line option or a Builder option, passed to the generator using the `PluggableWare::mp_WareEnv` structure and the `OPENFLUID_GetRunEnvironment()` accessor

**Comment by Arthoni** [comment]
## Fixes on previous specifications

### Current implementation
- [ ] Default behavior is to delete temp data from InterpGenerator
- [ ] InterpGenerator checks if variable `keep.dir.tmp` is set to true at finalizeRun to delete generator temp folder

### Extended use (in dedicated commit)
- [ ] Option `--keep-tmp-dir` or `-e` in command line to keep temp folders
- [ ] ? variable containing list of temp directories to be deleted (according to the env variable), so that delete step can be consistently externalized in the parent class. The only thing to do in each ware class is to fill the list with temporary paths of the current ware

**Comment by Arthoni** [comment]
General behavior stored in branch `auto-remove-all-tmp-files` (in `Arthoni/openfluid` fork) for further developments
