### ISSUE TITLE
Open-Builder close when cancelling 'Open Observer' menu item

### ISSUE THREAD

**Issue by eup31000** [OpenFLUID/openfluid#975]
After opening an existing simulator in OpenFluid-Builder, I tried to open an observer (before last menu item from Development menu).
As I have none defined, I get a dialog where I can only choose the Cancel option: when I do so (button 'Annuler' in french version), the full OpenFluid-Builder application exits instead of simply closing the dialog ...
![Observateur](https://user-images.githubusercontent.com/47326765/92608762-0d570d80-f2b6-11ea-9f4a-361c76bc191c.png)

**Comment by Arthoni** [comment]
Replicated, closing due to app crash. Error message: 
`std ERROR: Can't open ware, path empty (sent by OpenFLUID framework, located at void openfluid::ui::waresdev::WareSrcWidgetCollection::openWare(openfluid::ware::WareType, const QString&))`
Identical error when cancelling the `open a simulator...` dialog
